[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "FV7AuEp4Z8XUhsnW3pjtgpks8H4gphkWuvZLpvDj8dLD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"

